#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabbit
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/CodeGen.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0.0.0")]
    public class CodeGen_cshtml : System.Web.WebPages.WebPage
    {
#line hidden

    string code_type = "Web Form", code = "", file_name = "", msg = "", 
           actions = "Default, Create, Edit, Delete";

    void page_load()
    {        
        code = Rabbit.CodeGen.GetTemplate(code_type, file_name, actions);
        if (!IsPost)
        {
            file_name = Rabbit.CodeGen.GetDefaultFileName(code_type);
        }
    }

    void code_type_click()
    {
        file_name = Rabbit.CodeGen.GetDefaultFileName(code_type); 
    }
    
    //void refresh_click()
    //{
    //    code = Rabbit.CodeGen.GetTemplate(code_type, file_name, actions);
    //}
    
    void save_click()
    {
        if (file_name.IsEmpty())
        {
            msg = "File name is required.";
        }
        else {

            try
            {
                var fileName = Server.MapPath(file_name);
                var ncode = Request.Unvalidated("ncode");  
                code = ncode;
                Rabbit.CodeGen.SaveCode(code_type, Server.MapPath("~/"), fileName, ncode, actions);
                msg = "File saved.";
            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
        }
    }

                    // Resolve package relative syntax
                    // Also, if it comes from a static embedded resource, change the path accordingly
                    public override string Href(string virtualPath, params object[] pathParts) {
                        virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                        return base.Href(virtualPath, pathParts);
                    }
        public CodeGen_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


  
    
    ((IList<Tuple<string, string>>)PageData["BreadCrumbs"]).Add(Tuple.Create<string, string>("Rabbit Admin", "/_Admin/Rabbit"));
    ((IList<Tuple<string, string>>)PageData["BreadCrumbs"]).Add(Tuple.Create<string, string>("Generate Code", "/_Admin/Rabbit/CodeGen"));

    Rabbit.WebForm.Run(this);
    



WriteLiteral("\r\n");


DefineSection("Head", () => {

WriteLiteral("\r\n    <script src=\"http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.4.4.min.js\" typ" +
"e=\"text/javascript\"></script>\r\n    <script type=\"text/javascript\" src=\"");


                                   Write(Href("WebForms.js"));

WriteLiteral("\"></script>\r\n    <style type=\"text/css\">\r\n        h1 { margin-bottom: 20px;}\r\n   " +
"     input[type=\'text\']{width: 250px;}\r\n    </style>\r\n");


});

WriteLiteral(@"
<form method=""post"" action="""">

<h1>
    Rabbit Code Generator</h1>

<div style=""float:left;margin-bottom:10px;"">
    Select a code type: 
    <select id=""code_type"" name=""code_type"" data-autopostback=""true"">
    <option>Web Form</option>
    <option>MVC</option>
    <option>Unit Test</option>
    </select>
</div>
");


 if (code_type == "MVC")
{ 

WriteLiteral("<div style=\"float:left;margin-left:10px;\">\r\n    Controller: <input type=\"text\" na" +
"me=\"file_name\" value=\"");


                                                      Write(file_name);

WriteLiteral("\" />\r\n    Actions: <input type=\"text\" name=\"actions\" value=\"");


                                                 Write(actions);

WriteLiteral("\" />\r\n    <input id=\"refresh\" type=\"submit\" value=\"Refresh\" data-runat=\"server\"/>" +
"\r\n</div>\r\n");


}
else if (code_type == "Unit Test")
{

WriteLiteral("<div style=\"float:left;margin-left:10px\">\r\n    Test Name: <input type=\"text\" name" +
"=\"file_name\" value=\"");


                                                     Write(file_name);

WriteLiteral("\" />\r\n</div>\r\n");


}
else
{ 

WriteLiteral("<div style=\"float:left;margin-left:10px;\">\r\n    File Name: <input type=\"text\" nam" +
"e=\"file_name\" value=\"");


                                                     Write(file_name);

WriteLiteral("\" />\r\n</div>\r\n");


}

WriteLiteral("<div style=\"float:left;margin-left:10px;margin-bottom:10px;\">\r\n   <input id=\"save" +
"\" type=\"submit\" value=\"Save\" data-runat=\"server\"/>\r\n  <div id=\"msg\">");


           Write(msg);

WriteLiteral("</div>\r\n</div>\r\n<textarea name=\"ncode\" style=\"width:100%; border:1px solid #999; " +
"height:350px;\">");


                                                                           Write(code);

WriteLiteral("</textarea>\r\n\r\n</form>\r\n\r\n<script type=\"text/javascript\">\r\n    $(function () {\r\n " +
"       webForm.init();\r\n        $(\"#code_type\").val(\'");


                        Write(code_type);

WriteLiteral("\');\r\n    });\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
