#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabbit
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using Rabbit;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/Default.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0.0.0")]
    public class Default_cshtml : System.Web.WebPages.WebPage
    {
#line hidden

                    // Resolve package relative syntax
                    // Also, if it comes from a static embedded resource, change the path accordingly
                    public override string Href(string virtualPath, params object[] pathParts) {
                        virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                        return base.Href(virtualPath, pathParts);
                    }
        public Default_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



  
    
    ((IList<Tuple<string, string>>)PageData["BreadCrumbs"])
        .Add(Tuple.Create<string, string>("Rabbit Admin", "/_Admin/Rabbit"));
/*    
    if (IsPost)
    {
        Page.Modules = SiteEngine.SetModules(Request.Form["modules"]);
    }
    else 
    {
        Page.Modules = SiteEngine.GetModules();
    }

    var adminmenu = SiteEngine.RunHook("get_module_admin_menu", new List<string>()) as List<string>;   
*/


WriteLiteral(@"
<style type=""text/css"">
    h2{margin-top:30px}
    ul.adminmenu, ul.adminmenu li{margin-left:10px;}
</style>
<h1>Rabbit Framework Administration</h1>
<p>Rabbit Framework supports modules, plug-ins and templates. For more information, 
please visit <a href=""http://rabbit.codeplex.com"">Rabbit Framework</a>.</p>
<div style=""float:left;width:50%"">

<form method=""post"" action="""">

<h2>Modules</h2>
<p>Listed below are all available Rabbit modules. To disable a module, put a # in front of it.
The modules will be loaded using the order they appear in the list.</p>
<p><textarea name=""modules"" rows=""10"" cols=""40"">");


                                           Write(Page.Modules);

WriteLiteral(@"</textarea> </p>
<br /><br />
<input type=""submit"" value=""Save"" /> 
</form>
</div>

<div style=""float:left;padding-left:10px;"">
<h2>Module Admin</h2>
<p>Administrative links from modules.</p>
    <ul class=""adminmenu"">
    <li><a href=""/_Admin/Rabbit/Test"">Unit Test</a></li>
    <li><a href=""/_Admin/Rabbit/CodeGen"">Generate Code</a></li>
");



WriteLiteral("\r\n    </ul> \r\n</div> \r\n\r\n");


        }
    }
}
#pragma warning restore 1591
