#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabbit
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 2 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
    using Rabbit;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Default.cshtml")]
    public class Default : System.Web.WebPages.WebPage
    {

                // Resolve package relative syntax
                // Also, if it comes from a static embedded resource, change the path accordingly
                public override string Href(string virtualPath, params object[] pathParts) {
                    virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                    return base.Href(virtualPath, pathParts);
                }
        public Default()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 3 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
  
    
    ((IList<Tuple<string, string>>)PageData["BreadCrumbs"])
        .Add(Tuple.Create<string, string>("Rabbit Admin", "/_Admin/Rabbit"));

    var adminmenu = SiteEngine.RunHook("get_admin_menu", new List<string>()) as List<string>;   


            
            #line default
            #line hidden
WriteLiteral(@"
<style type=""text/css"">
    h2{margin-top:30px; margin-bottom:20px;}
    ul.adminmenu, ul.adminmenu li{margin-left:10px;margin-bottom:10px;}
</style>
<h1>Rabbit Framework Administration</h1>
<p>Rabbit Framework supports modules, plug-ins and templates. For more information, 
please visit <a href=""http://rabbit.codeplex.com"">Rabbit Framework</a>.</p>

<div style=""float:left;padding-left:10px;"">
<h2>Admin Links</h2>
    <ul class=""adminmenu"">
    <li><a href=""/_Admin/Rabbit/Test"">Unit Test</a></li>
    <li><a href=""/_Admin/Rabbit/CodeGen"">Generate Code</a></li>
");


            
            #line 24 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
 if (adminmenu.Count() > 0)
{ 
    foreach(var menu in adminmenu)
    {
        if(menu.Contains('|'))
        {
            var ss = menu.Split('|');

            
            #line default
            #line hidden
WriteLiteral("            <li class=\"admin-menu\"><a href=\"");


            
            #line 31 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
                                       Write(Href(ss[1]));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 31 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
                                                     Write(ss[0]);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 32 "E:\Users\Public\My Projects\Rabbit\Src\Rabbit\Default.cshtml"
        }
    } 
}

            
            #line default
            #line hidden
WriteLiteral("    </ul> \r\n</div> \r\n\r\n");


        }
    }
}
#pragma warning restore 1591
